### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by Serialc0de** [brentlintner/ocs-tracker#27]
Hello, can you insert an installation guide? Thank you

**Comment by brentlintner** [comment]
Thanks for creating an issue!

Do you mean installation guide for using the App itself or for setting up the code locally?

Reason I ask is there is https://github.com/brentlintner/ocs-tracker/blob/master/CONTRIBUTE.md for dev.

**Comment by Serialc0de** [comment]
> Thanks for creating an issue!
> 
> Do you mean installation guide for using the App itself or for setting up the code locally?
> 
> Reason I ask is there is https://github.com/brentlintner/ocs-tracker/blob/master/CONTRIBUTE.md for dev.

Thanks!

**Comment by Serialc0de** [comment]
@brentlintner I would like to ask you one last thing, if I wanted to create a site like OCS with all the varieties of plants and its features without commerce and various payments, which app can I install? I searched on github but these projects don't exist, how could I do? If you could point me to any app that I can install with these features that I have described, I would be grateful. Thank you in advance.
